version: "3.8"

services:
  contacts-sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: contacts-sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=qwertY@12345
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: 2GB
    volumes:
     - sqldata:/var/opt/mssql/server


  web-app:
    image: qceka88contactsdockercr.azurecr.io/contacts_azure_docker:v1
    container_name: web-app
    build:
      dockerfile: Contacts/Dockerfile
    domainname: "qceka88-docker"
    ports:
      - "80:80"
    restart: on-failure

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: qceka88contactsdockersan
