version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/staticfiles
    ports:
      - 8000:8000
    environment:
      - DEBUG=False

volumes:
  static:
